// Generated by scripts/generate_cms_narrations.mjs.
export const blogNarrationBySlug: Record<string, string> = {
  "solos-ghost-audit-pilot-rc2-dez-auditores": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-ghost-audit-pilot-rc2-dez-auditores.mp3",
  "solos-ghost-resolution-loop-selecionado-resolvido": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-ghost-resolution-loop-selecionado-resolvido.mp3",
  "solos-coeso-por-fora-modular-por-dentro": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-coeso-por-fora-modular-por-dentro.mp3",
  "solos-coracao-persistente-pulso-security-first": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-coracao-persistente-pulso-security-first.mp3",
  "fundraiser-seguranca-nova-fase-solos-luigi": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/fundraiser-seguranca-nova-fase-solos-luigi.mp3",
  "solos-v1-rc1-agencia-inspecionavel": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-v1-rc1-agencia-inspecionavel.mp3",
  "solos-pulso-rede-social-dados-humanos": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-pulso-rede-social-dados-humanos.mp3",
  "solos-heart-pass-quota-runtime-2026": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-heart-pass-quota-runtime-2026.mp3",
  "solos-heart-pass-quota-layer": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-heart-pass-quota-layer.mp3",
  "lbartes-luiz-manifesto-simbiose-pragmatica-ia": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/lbartes-luiz-manifesto-simbiose-pragmatica-ia.mp3",
  "solos-ghost-agente-operacional-readiness-2026": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-ghost-agente-operacional-readiness-2026.mp3",
  "ia-como-engenheiro-de-software-da-firma-case-prototipo-e-observabilidade": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/ia-como-engenheiro-de-software-da-firma-case-prototipo-e-observabilidade.mp3",
  "estrutura-vicaria-realidade-tentacao-cuidado-vontade": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/estrutura-vicaria-realidade-tentacao-cuidado-vontade.mp3",
  "prazer-eu-sou-lucifer-terapia-no-reino": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/prazer-eu-sou-lucifer-terapia-no-reino.mp3",
  "pronto-para-reinar-dialogo-filho-pai-orion": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/pronto-para-reinar-dialogo-filho-pai-orion.mp3",
  "legado-dos-perturbados-memoria-mito-relatos": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/legado-dos-perturbados-memoria-mito-relatos.mp3",
  "solos-ghost-prototipo-ia-funcional": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-ghost-prototipo-ia-funcional.mp3",
  "adon-aeve-mito-cosmologico-origem-abandono-transmutacao": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/adon-aeve-mito-cosmologico-origem-abandono-transmutacao.mp3",
  "solos-runtime-intermediario-operating-layer-linux": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-runtime-intermediario-operating-layer-linux.mp3",
  "estive-no-sheol-mundo-dos-mortos-mais-uma-vez": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/estive-no-sheol-mundo-dos-mortos-mais-uma-vez.mp3",
  "solos-colaboracao-aberta-e-a-nova-camada-operacional": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/solos-colaboracao-aberta-e-a-nova-camada-operacional.mp3",
  "capital-humano-na-era-da-ia-por-que-ciencia-criatividade-e-pesquisa-ficam-ainda-mais-valiosas": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/capital-humano-na-era-da-ia-por-que-ciencia-criatividade-e-pesquisa-ficam-ainda-mais-valiosas.mp3",
  "ias-androides-e-mineracao-de-dados-como-transformar-extracao-em-relacao-negociada": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/ias-androides-e-mineracao-de-dados-como-transformar-extracao-em-relacao-negociada.mp3",
  "manifesto-lbartes-luiz-simbiose-agencia-humana-e-futuro-hibrido": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/manifesto-lbartes-luiz-simbiose-agencia-humana-e-futuro-hibrido.mp3",
  "do-desenho-a-estampa": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/do-desenho-a-estampa.mp3",
  "como-montar-looks-street-casual-que-atraem-e-vendem": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/como-montar-looks-street-casual-que-atraem-e-vendem.mp3",
  "camisetas-sustentaveis-o-que-o-cliente-realmente-espera": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/camisetas-sustentaveis-o-que-o-cliente-realmente-espera.mp3",
  "estampas-vintage-e-nostalgia-pop": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/estampas-vintage-e-nostalgia-pop.mp3",
  "bem-vindo-a-lbartes-luiz-arte-que-veste-atitude": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/blog/bem-vindo-a-lbartes-luiz-arte-que-veste-atitude.mp3"
};

export const productNarrationBySlug: Record<string, string> = {
  "hard-rock-70": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/hard-rock-70.mp3",
  "hard-rock-70-thin": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/hard-rock-70-thin.mp3",
  "miley-curly": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/miley-curly.mp3",
  "leao-de-juda": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/leao-de-juda.mp3",
  "amorzinho": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/amorzinho.mp3",
  "logo-apos-a-tempestade": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/logo-apos-a-tempestade.mp3",
  "coracao-s2": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/coracao-s2.mp3",
  "elove": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/elove.mp3",
  "turne-do-amor": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/turne-do-amor.mp3",
  "noizes": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/noizes.mp3",
  "with-love": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/with-love.mp3",
  "solos-heart-pass": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/solos-heart-pass.mp3",
  "nfts-opensea": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/products/nfts-opensea.mp3"
};

export const pageNarrationByRoute: Record<string, string> = {
  "/solos": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/solos.mp3",
  "/roadmap": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/roadmap.mp3",
  "/manifesto": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/manifesto.mp3",
  "/manifesto/anexo": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/manifesto-anexo.mp3",
  "/whitepaper": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/whitepaper.mp3",
  "/solos/fundadores": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/solos-fundadores.mp3",
  "/solos/pulso": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/solos-pulso.mp3",
  "/luigi": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/cantinho-luigi.mp3",
  "/produtos": "https://bkmzbbohunqkmcaeppqf.supabase.co/storage/v1/object/public/audio/pages/produtos.mp3"
};
